sbatch --array=[0-999] -t 0-4:00 --mem=10G run_and_analysis_parallel_synthetic.sh  --T=50 --n=50 --recruit_n=50 --synthetic_mode=delayed_1_dosage_paper --steepness=0.5 --inference_func_filename="functions_to_pass_to_analysis/synthetic_get_least_squares_loss_inference_paper_simulation.py" --theta_calculation_func_filename="functions_to_pass_to_analysis/synthetic_estimate_theta_least_squares_paper_simulation.py" --alg_update_func_args_action_prob_index=-1 --alg_update_func_args_action_prob_times_index=-1
sbatch --array=[0-999] -t 0-4:00 --mem=20G run_and_analysis_parallel_synthetic.sh  --T=50 --n=100 --recruit_n=100 --synthetic_mode=delayed_1_dosage_paper --steepness=0.5 --inference_func_filename="functions_to_pass_to_analysis/synthetic_get_least_squares_loss_inference_paper_simulation.py" --theta_calculation_func_filename="functions_to_pass_to_analysis/synthetic_estimate_theta_least_squares_paper_simulation.py" --alg_update_func_args_action_prob_index=-1 --alg_update_func_args_action_prob_times_index=-1
sbatch --array=[0-999] -t 0-4:00 --mem=100G run_and_analysis_parallel_synthetic.sh  --T=50 --n=500 --recruit_n=500 --synthetic_mode=delayed_1_dosage_paper --steepness=0.5 --inference_func_filename="functions_to_pass_to_analysis/synthetic_get_least_squares_loss_inference_paper_simulation.py" --theta_calculation_func_filename="functions_to_pass_to_analysis/synthetic_estimate_theta_least_squares_paper_simulation.py" --alg_update_func_args_action_prob_index=-1 --alg_update_func_args_action_prob_times_index=-1

sbatch --array=[0-999] -t 0-4:00 --mem=10G run_and_analysis_parallel_synthetic.sh  --T=50 --n=50 --recruit_n=50 --synthetic_mode=delayed_1_dosage_paper --steepness=1.0 --inference_func_filename="functions_to_pass_to_analysis/synthetic_get_least_squares_loss_inference_paper_simulation.py" --theta_calculation_func_filename="functions_to_pass_to_analysis/synthetic_estimate_theta_least_squares_paper_simulation.py" --alg_update_func_args_action_prob_index=-1 --alg_update_func_args_action_prob_times_index=-1
sbatch --array=[0-999] -t 0-4:00 --mem=20G run_and_analysis_parallel_synthetic.sh  --T=50 --n=100 --recruit_n=100 --synthetic_mode=delayed_1_dosage_paper --steepness=1.0 --inference_func_filename="functions_to_pass_to_analysis/synthetic_get_least_squares_loss_inference_paper_simulation.py" --theta_calculation_func_filename="functions_to_pass_to_analysis/synthetic_estimate_theta_least_squares_paper_simulation.py" --alg_update_func_args_action_prob_index=-1 --alg_update_func_args_action_prob_times_index=-1
sbatch --array=[0-999] -t 0-4:00 --mem=100G run_and_analysis_parallel_synthetic.sh  --T=50 --n=500 --recruit_n=500 --synthetic_mode=delayed_1_dosage_paper --steepness=1.0 --inference_func_filename="functions_to_pass_to_analysis/synthetic_get_least_squares_loss_inference_paper_simulation.py" --theta_calculation_func_filename="functions_to_pass_to_analysis/synthetic_estimate_theta_least_squares_paper_simulation.py" --alg_update_func_args_action_prob_index=-1 --alg_update_func_args_action_prob_times_index=-1

sbatch --array=[0-999] -t 0-4:00 --mem=10G run_and_analysis_parallel_synthetic.sh  --T=50 --n=50 --recruit_n=50 --synthetic_mode=delayed_1_dosage_paper --steepness=5.0 --inference_func_filename="functions_to_pass_to_analysis/synthetic_get_least_squares_loss_inference_paper_simulation.py" --theta_calculation_func_filename="functions_to_pass_to_analysis/synthetic_estimate_theta_least_squares_paper_simulation.py" --alg_update_func_args_action_prob_index=-1 --alg_update_func_args_action_prob_times_index=-1
sbatch --array=[0-999] -t 0-4:00 --mem=20G run_and_analysis_parallel_synthetic.sh  --T=50 --n=100 --recruit_n=100 --synthetic_mode=delayed_1_dosage_paper --steepness=5.0 --inference_func_filename="functions_to_pass_to_analysis/synthetic_get_least_squares_loss_inference_paper_simulation.py" --theta_calculation_func_filename="functions_to_pass_to_analysis/synthetic_estimate_theta_least_squares_paper_simulation.py" --alg_update_func_args_action_prob_index=-1 --alg_update_func_args_action_prob_times_index=-1
sbatch --array=[0-999] -t 0-4:00 --mem=100G run_and_analysis_parallel_synthetic.sh  --T=50 --n=500 --recruit_n=500 --synthetic_mode=delayed_1_dosage_paper --steepness=5.0 --inference_func_filename="functions_to_pass_to_analysis/synthetic_get_least_squares_loss_inference_paper_simulation.py" --theta_calculation_func_filename="functions_to_pass_to_analysis/synthetic_estimate_theta_least_squares_paper_simulation.py" --alg_update_func_args_action_prob_index=-1 --alg_update_func_args_action_prob_times_index=-1

sbatch --array=[0-999] -t 0-4:00 --mem=10G run_and_analysis_parallel_synthetic.sh  --T=50 --n=50 --recruit_n=50 --synthetic_mode=delayed_5_dosage_paper --steepness=0.5 --inference_func_filename="functions_to_pass_to_analysis/synthetic_get_least_squares_loss_inference_paper_simulation.py" --theta_calculation_func_filename="functions_to_pass_to_analysis/synthetic_estimate_theta_least_squares_paper_simulation.py" --alg_update_func_args_action_prob_index=-1 --alg_update_func_args_action_prob_times_index=-1
sbatch --array=[0-999] -t 0-4:00 --mem=20G run_and_analysis_parallel_synthetic.sh  --T=50 --n=100 --recruit_n=100 --synthetic_mode=delayed_5_dosage_paper --steepness=0.5 --inference_func_filename="functions_to_pass_to_analysis/synthetic_get_least_squares_loss_inference_paper_simulation.py" --theta_calculation_func_filename="functions_to_pass_to_analysis/synthetic_estimate_theta_least_squares_paper_simulation.py" --alg_update_func_args_action_prob_index=-1 --alg_update_func_args_action_prob_times_index=-1
sbatch --array=[0-999] -t 0-4:00 --mem=100G run_and_analysis_parallel_synthetic.sh  --T=50 --n=500 --recruit_n=500 --synthetic_mode=delayed_5_dosage_paper --steepness=0.5 --inference_func_filename="functions_to_pass_to_analysis/synthetic_get_least_squares_loss_inference_paper_simulation.py" --theta_calculation_func_filename="functions_to_pass_to_analysis/synthetic_estimate_theta_least_squares_paper_simulation.py" --alg_update_func_args_action_prob_index=-1 --alg_update_func_args_action_prob_times_index=-1

sbatch --array=[0-999] -t 0-4:00 --mem=10G run_and_analysis_parallel_synthetic.sh  --T=50 --n=50 --recruit_n=50 --synthetic_mode=delayed_5_dosage_paper --steepness=1.0 --inference_func_filename="functions_to_pass_to_analysis/synthetic_get_least_squares_loss_inference_paper_simulation.py" --theta_calculation_func_filename="functions_to_pass_to_analysis/synthetic_estimate_theta_least_squares_paper_simulation.py" --alg_update_func_args_action_prob_index=-1 --alg_update_func_args_action_prob_times_index=-1
sbatch --array=[0-999] -t 0-4:00 --mem=20G run_and_analysis_parallel_synthetic.sh  --T=50 --n=100 --recruit_n=100 --synthetic_mode=delayed_5_dosage_paper --steepness=1.0 --inference_func_filename="functions_to_pass_to_analysis/synthetic_get_least_squares_loss_inference_paper_simulation.py" --theta_calculation_func_filename="functions_to_pass_to_analysis/synthetic_estimate_theta_least_squares_paper_simulation.py" --alg_update_func_args_action_prob_index=-1 --alg_update_func_args_action_prob_times_index=-1
sbatch --array=[0-999] -t 0-4:00 --mem=100G run_and_analysis_parallel_synthetic.sh  --T=50 --n=500 --recruit_n=500 --synthetic_mode=delayed_5_dosage_paper --steepness=1.0 --inference_func_filename="functions_to_pass_to_analysis/synthetic_get_least_squares_loss_inference_paper_simulation.py" --theta_calculation_func_filename="functions_to_pass_to_analysis/synthetic_estimate_theta_least_squares_paper_simulation.py" --alg_update_func_args_action_prob_index=-1 --alg_update_func_args_action_prob_times_index=-1

sbatch --array=[0-999] -t 0-4:00 --mem=10G run_and_analysis_parallel_synthetic.sh  --T=50 --n=50 --recruit_n=50 --synthetic_mode=delayed_5_dosage_paper --steepness=5.0 --inference_func_filename="functions_to_pass_to_analysis/synthetic_get_least_squares_loss_inference_paper_simulation.py" --theta_calculation_func_filename="functions_to_pass_to_analysis/synthetic_estimate_theta_least_squares_paper_simulation.py" --alg_update_func_args_action_prob_index=-1 --alg_update_func_args_action_prob_times_index=-1
sbatch --array=[0-999] -t 0-4:00 --mem=20G run_and_analysis_parallel_synthetic.sh  --T=50 --n=100 --recruit_n=100 --synthetic_mode=delayed_5_dosage_paper --steepness=5.0 --inference_func_filename="functions_to_pass_to_analysis/synthetic_get_least_squares_loss_inference_paper_simulation.py" --theta_calculation_func_filename="functions_to_pass_to_analysis/synthetic_estimate_theta_least_squares_paper_simulation.py" --alg_update_func_args_action_prob_index=-1 --alg_update_func_args_action_prob_times_index=-1
sbatch --array=[0-999] -t 0-4:00 --mem=100G run_and_analysis_parallel_synthetic.sh  --T=50 --n=500 --recruit_n=500 --synthetic_mode=delayed_5_dosage_paper --steepness=5.0 --inference_func_filename="functions_to_pass_to_analysis/synthetic_get_least_squares_loss_inference_paper_simulation.py" --theta_calculation_func_filename="functions_to_pass_to_analysis/synthetic_estimate_theta_least_squares_paper_simulation.py" --alg_update_func_args_action_prob_index=-1 --alg_update_func_args_action_prob_times_index=-1
# EXTRA ONE FOLLOWS
sbatch --array=[0-999] -t 0-8:00 --mem=160G run_and_analysis_parallel_synthetic.sh  --T=50 --n=1000 --recruit_n=1000 --synthetic_mode=delayed_5_dosage_paper --steepness=5.0 --inference_func_filename="functions_to_pass_to_analysis/synthetic_get_least_squares_loss_inference_paper_simulation.py" --theta_calculation_func_filename="functions_to_pass_to_analysis/synthetic_estimate_theta_least_squares_paper_simulation.py" --alg_update_func_args_action_prob_index=-1 --alg_update_func_args_action_prob_times_index=-1