name: Run Integration Tests on PRs

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          python-version: '3.10'

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Run integration tests
        # continue-on-error: true
        run: uv run python -m pytest tests/integration_tests

      # - name: Check simulated_data directory contents
      #   run: |
      #     ls -Rla /home/runner/work/adaptive-sandwich/adaptive-sandwich/simulated_data || echo "Directory does not exist or is empty"